// packages/kiwicaptcha-solid/examples/LoginForm.tsx
import { createSignal, Show } from "solid-js";
import { KiwiCaptcha, type KiwiSolidControls } from "@kiwicaptcha/solid";

/** The four-setting quickstart with a token field. */
export function LoginForm() {
  let controls: KiwiSolidControls | undefined;
  const [token, setToken] = createSignal("");
  const [error, setError] = createSignal<string | null>(null);

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        // POST the form with token in the kiwi__token field.
      }}
    >
      <KiwiCaptcha
        ref={(c) => (controls = c)}
        endpoint="/api/kcaptcha/challenge"
        sitekey="pk-live-1"
        scope="login"
        lang="en"
        onVerify={(t) => setToken(t)}
        onError={(m) => setError(m)}
        onExpire={() => controls?.reset()}
      />
      <Show when={error()}>
        <p role="alert">{error()}</p>
      </Show>
      <input type="hidden" name="kiwi__token" value={token()} />
      <button disabled={token() === ""}>Sign in</button>
    </form>
  );
}

// packages/kiwicaptcha-svelte/examples/LoginForm.svelte
<script lang="ts">
  import { KiwiCaptcha } from "@kiwicaptcha/svelte";

  let token = $state("");
  let error = $state<string | null>(null);
  let widget: { reset(): void };

  function submit(event: SubmitEvent): void {
    event.preventDefault();
    // POST the form with token in the kiwi__token field.
    void token;
  }
</script>

<form onsubmit={submit}>
  <KiwiCaptcha
    bind:this={widget}
    endpoint="/api/kcaptcha/challenge"
    sitekey="pk-live-1"
    scope="login"
    lang="en"
    onverify={(t) => (token = t)}
    onerror={(m) => (error = m)}
    onexpire={() => widget?.reset()}
  />
  {#if error}
    <p role="alert">{error}</p>
  {/if}
  <input type="hidden" name="kiwi__token" value={token} />
  <button disabled={token === ""}>Sign in</button>
</form>
