// packages/kiwicaptcha-svelte/src/KiwiCaptcha.svelte
<script lang="ts">
  import {
    renderKiwiCaptcha,
    type KiwiErrorDetail,
    type KiwiRenderOptions,
    type KiwiRetryDetail,
    type KiwiVerifiedDetail,
    type KiwiWidgetHandle,
  } from "@kiwicaptcha/client-core";
  import { onMount } from "svelte";

  /**
   * The KiwiCaptcha widget as a Svelte 5 component.
   *
   * Props are the core render options (endpoint, sitekey, scope, lang
   * is the four-setting quickstart) plus the callback props named
   * `onverify`, `onerror`, `onexpire`, `onready`, `onverifying`,
   * `onretry`, `onworkerunavailable` and `onexecutionunavailable`.
   * Bind the component for reset/execute/getResponse/isExpired.
   */
  interface Props extends KiwiRenderOptions {
    class?: string;
    style?: string;
    onready?: (scope: string) => void;
    onverifying?: (scope: string) => void;
    onverify?: (token: string, detail: KiwiVerifiedDetail) => void;
    onerror?: (message: string, detail: KiwiErrorDetail) => void;
    onexpire?: (scope: string) => void;
    onretry?: (detail: KiwiRetryDetail) => void;
    onworkerunavailable?: (reason: string, scope: string) => void;
    onexecutionunavailable?: (reason: string, scope: string) => void;
  }

  let {
    class: className = "",
    style = "",
    onready,
    onverifying,
    onverify,
    onerror,
    onexpire,
    onretry,
    onworkerunavailable,
    onexecutionunavailable,
    ...config
  }: Props = $props();

  let el: HTMLDivElement;
  let handle: KiwiWidgetHandle | null = null;

  /** Cancel the current run and acquire a fresh challenge. */
  export function reset(): void {
    handle?.reset();
  }
  /** The verified token, or "" while unverified or expired. */
  export function getResponse(): string {
    return handle?.getResponse() ?? "";
  }
  /** Whether the last verified token has expired. */
  export function isExpired(): boolean {
    return handle?.isExpired() ?? false;
  }
  /** Start or await the solve; resolves the token. */
  export function execute(): Promise<string> {
    return handle
      ? handle.execute()
      : Promise.reject(new Error("kiwicaptcha: widget not mounted"));
  }

  onMount(() => {
    // Callbacks read the current prop value at event time, so a parent
    // may pass fresh inline functions without rebuilding the widget.
    // The config fields are captured once: a changed config is expressed
    // as a keyed re-mount ({#key}) by the caller.
    const options: KiwiRenderOptions = {
      ...config,
      onReady: (scope) => onready?.(scope),
      onVerifying: (scope) => onverifying?.(scope),
      onVerify: (token, detail) => onverify?.(token, detail),
      onError: (message, detail) => onerror?.(message, detail),
      onExpire: (scope) => onexpire?.(scope),
      onRetry: (detail) => onretry?.(detail),
      onWorkerUnavailable: (reason, scope) => onworkerunavailable?.(reason, scope),
      onExecutionUnavailable: (reason, scope) => onexecutionunavailable?.(reason, scope),
    };
    try {
      handle = renderKiwiCaptcha(el, options);
    } catch {
      void loadAndRender(el, options).then((h) => {
        handle = h;
      });
    }
    return () => {
      handle?.destroy();
      handle = null;
    };
  });

  async function loadAndRender(
    node: HTMLElement,
    options: KiwiRenderOptions,
  ): Promise<KiwiWidgetHandle> {
    const { loadKiwiCaptcha } = await import("@kiwicaptcha/client-core");
    const api = await loadKiwiCaptcha();
    return renderKiwiCaptcha(node, { ...options, api });
  }
</script>

<div bind:this={el} class={className} {style}></div>

// packages/kiwicaptcha-solid/src/KiwiCaptcha.tsx
import {
  onCleanup,
  onMount,
  type JSX,
} from "solid-js";
import {
  loadKiwiCaptcha,
  renderKiwiCaptcha,
  type KiwiRenderOptions,
  type KiwiWidgetHandle,
} from "@kiwicaptcha/client-core";

/** Imperative controls delivered through the ref prop. */
export interface KiwiSolidControls {
  getResponse(): string;
  isExpired(): boolean;
  reset(): void;
  execute(): Promise<string>;
}

export interface KiwiCaptchaProps extends KiwiRenderOptions {
  class?: string;
  style?: JSX.CSSProperties | string;
  /** Receives the imperative controls once the widget is mounted. */
  ref?: (controls: KiwiSolidControls) => void;
}

/**
 * The KiwiCaptcha widget as a SolidJS component.
 *
 * Config props (endpoint, sitekey, scope, lang is the four-setting
 * quickstart) are captured when the widget mounts; callback props stay
 * live, so parents may pass fresh inline functions on every render.
 * Cleanup destroys the driver record when the component unmounts.
 */
export function KiwiCaptcha(props: KiwiCaptchaProps): JSX.Element {
  let el: HTMLDivElement | undefined;
  let handle: KiwiWidgetHandle | null = null;

  const controls: KiwiSolidControls = {
    getResponse: () => handle?.getResponse() ?? "",
    isExpired: () => handle?.isExpired() ?? false,
    reset: () => handle?.reset(),
    execute: () =>
      handle
        ? handle.execute()
        : Promise.reject(new Error("kiwicaptcha: widget not mounted")),
  };

  onMount(() => {
    // Config read once at mount; callbacks delegate through the props
    // proxy so the latest values are used at event time.
    const {
      class: _class,
      style: _style,
      ref: _ref,
      onReady,
      onVerifying,
      onVerify,
      onError,
      onExpire,
      onRetry,
      onWorkerUnavailable,
      onExecutionUnavailable,
      ...config
    } = props;
    const options: KiwiRenderOptions = {
      ...config,
      onReady: (scope) => onReady?.(scope),
      onVerifying: (scope) => onVerifying?.(scope),
      onVerify: (token, detail) => onVerify?.(token, detail),
      onError: (message, detail) => onError?.(message, detail),
      onExpire: (scope) => onExpire?.(scope),
      onRetry: (detail) => onRetry?.(detail),
      onWorkerUnavailable: (reason, scope) => onWorkerUnavailable?.(reason, scope),
      onExecutionUnavailable: (reason, scope) => onExecutionUnavailable?.(reason, scope),
    };
    try {
      handle = renderKiwiCaptcha(el as HTMLElement, options);
    } catch {
      void loadKiwiCaptcha().then((api) => {
        handle = renderKiwiCaptcha(el as HTMLElement, { ...options, api });
      });
    }
    props.ref?.(controls);
  });

  onCleanup(() => {
    handle?.destroy();
    handle = null;
  });

  return <div ref={el} class={props.class} style={props.style} />;
}
