// packages/kiwicaptcha-vue/src/KiwiCaptcha.vue
<script setup lang="ts">
import { useKiwiCaptcha, type UseKiwiCaptchaOptions } from "./useKiwiCaptcha";
import type {
  KiwiErrorDetail,
  KiwiRetryDetail,
  KiwiVerifiedDetail,
} from "@kiwicaptcha/client-core";

/**
 * The KiwiCaptcha widget as a Vue 3 component.
 *
 * Props are the core render options (the four-setting quickstart is
 * endpoint, sitekey, scope, lang) plus the loader controls. Lifecycle
 * events surface as Vue emits; the widget handle is exposed through
 * template refs for reset/execute/getResponse/isExpired.
 */
const props = withDefaults(defineProps<UseKiwiCaptchaOptions>(), {
  // Vue casts absent Boolean-capable props to false; an explicit
  // undefined default keeps the core's own semantics instead
  // (buildMarkup must default to true, responseField to the alias write).
  buildMarkup: undefined,
  responseField: undefined,
  execution: undefined,
  api: undefined,
});

const emit = defineEmits<{
  ready: [scope: string];
  verifying: [scope: string];
  verify: [token: string, detail: KiwiVerifiedDetail];
  error: [message: string, detail: KiwiErrorDetail];
  expire: [scope: string];
  retry: [detail: KiwiRetryDetail];
  workerUnavailable: [reason: string, scope: string];
  executionUnavailable: [reason: string, scope: string];
}>();

const { containerRef, ready, execute, reset, getResponse, isExpired } =
  useKiwiCaptcha(() => ({
    ...props,
    onReady: (scope) => emit("ready", scope),
    onVerifying: (scope) => emit("verifying", scope),
    onVerify: (token, detail) => emit("verify", token, detail),
    onError: (message, detail) => emit("error", message, detail),
    onExpire: (scope) => emit("expire", scope),
    onRetry: (detail) => emit("retry", detail),
    onWorkerUnavailable: (reason, scope) => emit("workerUnavailable", reason, scope),
    onExecutionUnavailable: (reason, scope) => emit("executionUnavailable", reason, scope),
  }));

defineExpose({ ready, execute, reset, getResponse, isExpired });
</script>

<template>
  <div ref="containerRef" class="kiwi-vue"></div>
</template>

// packages/kiwicaptcha-svelte/src/KiwiCaptcha.svelte
<script lang="ts">
  import {
    renderKiwiCaptcha,
    type KiwiErrorDetail,
    type KiwiRenderOptions,
    type KiwiRetryDetail,
    type KiwiVerifiedDetail,
    type KiwiWidgetHandle,
  } from "@kiwicaptcha/client-core";
  import { onMount } from "svelte";

  /**
   * The KiwiCaptcha widget as a Svelte 5 component.
   *
   * Props are the core render options (endpoint, sitekey, scope, lang
   * is the four-setting quickstart) plus the callback props named
   * `onverify`, `onerror`, `onexpire`, `onready`, `onverifying`,
   * `onretry`, `onworkerunavailable` and `onexecutionunavailable`.
   * Bind the component for reset/execute/getResponse/isExpired.
   */
  interface Props extends KiwiRenderOptions {
    class?: string;
    style?: string;
    onready?: (scope: string) => void;
    onverifying?: (scope: string) => void;
    onverify?: (token: string, detail: KiwiVerifiedDetail) => void;
    onerror?: (message: string, detail: KiwiErrorDetail) => void;
    onexpire?: (scope: string) => void;
    onretry?: (detail: KiwiRetryDetail) => void;
    onworkerunavailable?: (reason: string, scope: string) => void;
    onexecutionunavailable?: (reason: string, scope: string) => void;
  }

  let {
    class: className = "",
    style = "",
    onready,
    onverifying,
    onverify,
    onerror,
    onexpire,
    onretry,
    onworkerunavailable,
    onexecutionunavailable,
    ...config
  }: Props = $props();

  let el: HTMLDivElement;
  let handle: KiwiWidgetHandle | null = null;

  /** Cancel the current run and acquire a fresh challenge. */
  export function reset(): void {
    handle?.reset();
  }
  /** The verified token, or "" while unverified or expired. */
  export function getResponse(): string {
    return handle?.getResponse() ?? "";
  }
  /** Whether the last verified token has expired. */
  export function isExpired(): boolean {
    return handle?.isExpired() ?? false;
  }
  /** Start or await the solve; resolves the token. */
  export function execute(): Promise<string> {
    return handle
      ? handle.execute()
      : Promise.reject(new Error("kiwicaptcha: widget not mounted"));
  }

  onMount(() => {
    // Callbacks read the current prop value at event time, so a parent
    // may pass fresh inline functions without rebuilding the widget.
    // The config fields are captured once: a changed config is expressed
    // as a keyed re-mount ({#key}) by the caller.
    const options: KiwiRenderOptions = {
      ...config,
      onReady: (scope) => onready?.(scope),
      onVerifying: (scope) => onverifying?.(scope),
      onVerify: (token, detail) => onverify?.(token, detail),
      onError: (message, detail) => onerror?.(message, detail),
      onExpire: (scope) => onexpire?.(scope),
      onRetry: (detail) => onretry?.(detail),
      onWorkerUnavailable: (reason, scope) => onworkerunavailable?.(reason, scope),
      onExecutionUnavailable: (reason, scope) => onexecutionunavailable?.(reason, scope),
    };
    try {
      handle = renderKiwiCaptcha(el, options);
    } catch {
      void loadAndRender(el, options).then((h) => {
        handle = h;
      });
    }
    return () => {
      handle?.destroy();
      handle = null;
    };
  });

  async function loadAndRender(
    node: HTMLElement,
    options: KiwiRenderOptions,
  ): Promise<KiwiWidgetHandle> {
    const { loadKiwiCaptcha } = await import("@kiwicaptcha/client-core");
    const api = await loadKiwiCaptcha();
    return renderKiwiCaptcha(node, { ...options, api });
  }
</script>

<div bind:this={el} class={className} {style}></div>
